export const tasks = [
    {
      id: "task-1",
      projectId: "1",
      title: "Design homepage",
      description: "Create the homepage UI",
      status: "todo",
      priority: "high",
      assignee: "Harshit",
    },
    {
      id: "task-2",
      projectId: "1",
      title: "Create authentication",
      description: "Implement login and signup UI",
      status: "in-progress",
      priority: "high",
      assignee: "Rahul",
    },
    {
      id: "task-3",
      projectId: "1",
      title: "Create database schema",
      description: "Design the initial database structure",
      status: "todo",
      priority: "medium",
      assignee: "Aman",
    },
    {
      id: "task-4",
      projectId: "1",
      title: "Setup project repository",
      description: "Initialize Git repository",
      status: "done",
      priority: "low",
      assignee: "Harshit",
    },
    {
      id: "task-5",
      projectId: "1",
      title: "Build dashboard",
      description: "Create dashboard components",
      status: "in-progress",
      priority: "medium",
      assignee: "Rahul",
    },
  ];